### ISSUE TITLE
Pluto 24v3.1 QA

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#1177]
This issue will serve as both the issue for QA of draft 1 and the parent issue of any subsequent reviews

**Comment by caseysmithpgh** [comment]
### Pinning EDes versions for minor 

| PLUTO Version | GIS EDes Version | DE EDes Version |
| --- | --- | --- |
| 24v3 | 9/4 | 9/4 |
| 24v3.1 | 9/4 | 10/4 |

This time around the EDes version did not change between 24v3 and 24v3.1, however according to the qa page the source data was re-pulled from DO before building 24v3.1. The intention for minor was to only change zoning data, so is it possible for DE to pin the major EDes version for the subsequent minor builds? 

Since it's the same data and therefore there were no value changes, this won't be cause for a rebuild.

@fvankrieken 
FYI @croswell81 @jackrosacker

**Comment by fvankrieken** [comment]
Looks like in the recipe, we've specified that edes gets updated for minor updates

https://github.com/NYCPlanning/data-engineering/blob/main/products/pluto/recipe-minor.yml

Looks like this was the case back closer to when we started doing minors as well

https://github.com/NYCPlanning/db-pluto/issues/441

Seems like regardless we should also remove edes from the ztl data loading action? It's there now (gets grabbed from the do staging folder like the others)

**Comment by caseysmithpgh** [comment]
### PLUTO 24v3.1 QA flagged

### Summary:
FAIL - DTM Geometry Issue

### Details:
A few weeks back we encountered an issue where our DTM pull script was grabbing inaccurate geometry (ESRI's fault). I believe this caused at least one rebuild in the past few weeks. It's once again rearing it's ugly head, but what's interesting is that the pluto shp does not seem to be impacted. 

According to the QA app the DTM version used in 24v3.1 was `20240910`. Please investigate how the outputs seemingly ended up with two different versions of the tax lots. 

| dataset | record count | dtm issue |
| --- | --- | --- |
| mappluto shp | 856,856 | None |
| mappluto gdb | 856,856 | Geometry Issue |
| mappluto unclipped shp | 857,073 | Geometry Issue |
| mappluto unclipped gdb | 857,073 | Geometry Issue |

![Image](https://github.com/user-attachments/assets/4e84e5fa-cd19-45ed-a95c-39a16eee24f8)
![Image](https://github.com/user-attachments/assets/ebf00698-7759-4ef2-b9b7-5889575c869c)

@fvankrieken 
FYI @croswell81 @jackrosacker

**Comment by fvankrieken** [comment]
Hi @caseysmithpgh - the files actually are consisten with each other, both have the odd shapes. The reason they appear different seems to be ordering. Looking at the shapefile, if you turn down the opacity, it's apparent that they overlap

![Image](https://github.com/user-attachments/assets/6ad43802-7b41-47c3-9485-12d2ec980b97)

So the large "lot" has the odd-shaped cutouts, while the individual smaller lots seem to have the right shape. The gdb shows the same

![Image](https://github.com/user-attachments/assets/2241765e-111e-47b6-a794-47d3433b80c6)

**Comment by caseysmithpgh** [comment]
Can confirm that Finn is correct, all version of 24v3.1 contain inaccurate tax lot geometry.  DOF sources were static from 24v3, meaning this issue was present in that release as well. 

Since we already published 24v3 with this issue, I believe we are clear to proceed with publishing 24v3.1 as is. @croswell81 awaiting your signoff to proceed.

**Comment by caseysmithpgh** [comment]
@fvankrieken Matt signed off on this version. Please promote to /publish

**Comment by fvankrieken** [comment]
Done!

**Comment by caseysmithpgh** [comment]
QA complete; data is in the process of being published to Bytes of the Big Apple.
