### ISSUE TITLE
FacDB 24v2 QA - draft 3

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#1206]
FacDB page on QA app [here](https://de-qaqc.nycplanningdigital.com/?page=Facilities+DB)

**Comment by caseysmithpgh** [comment]
### FacDB 24v2 Draft 3 QA 

#### Results: 
**PASSES**,  pending DE final review of below details

#### Summary: 
- No concerns over key facsubgrps (i.e. police, fire, courts, etc.)
- A few qc_classification significant diff/ percent changes. Likely fine, but were all PARKS AND PLAZA facgroups, so worth DE taking a final look. See table details below for notes. 
- qc_captyp: Seats saw a 5567 count drop, seems reasonable, but worth having DE final approval. 

#### Details
| facdomain | facgroup | facsubgrp | count_old | dif | Percent absolute dif | Notes |
| - | - | - | - | - | - | - |
| PARKS, GARDENS, AND HISTORICAL SITES |PARKS AND PLAZA | UNDEVELOPED | -54 | -18 | 3333% | Decrease seems logical, but large pct change. Matt previously mentioned garden losses |
| PARKS, GARDENS, AND HISTORICAL SITES | PARKS AND PLAZA	| PRESERVES AND CONSERVATION AREAS | 114 | 11 | 965% | We love conservation areas, but large pct increase |
| PARKS, GARDENS, AND HISTORICAL SITES | PARKS AND PLAZA | CEMETERIES | 14 | -1 | 714% | Need to confirm there was a merge, because cemeteries don’t just disappear |
| PARKS, GARDENS, AND HISTORICAL SITES | PARKS AND PLAZA | PARKS | 430 | 30 | 698% | Significant increase, could be associated with negative change in UNDEVELOPED subgrp |

@damonmcc 
FYI @croswell81 @jackrosacker

**Comment by damonmcc** [comment]
- `UNDEVELOPED` and `CEMETERIES`
  - these are 1-to-1 with a `typecategory` value from `dpr_parksproperties` and are created during [`dpr_parksproperties.sql`](https://github.com/NYCPlanning/data-engineering/blob/main/products/facilities/facdb/sql/pipelines/dpr_parksproperties.sql)
  - their changes are due to real changes in source data
- `PRESERVES AND CONSERVATION AREAS` increased by 11
  - comes from three source datasets: `dpr_parksproperties, nysparks_parks, nysdec_lands, dcp_colp`
  - from `dpr_parksproperties` where `typecategory = 'Nature Area'`, the source data count increased by 7


| typecategory                |   old |   new |   count_change |
|:----------------------------|------:|------:|---------------:|
| Triangle/Plaza              |   351 |   349 |             -2 |
| Garden                      |   348 |   349 |              1 |
| Neighborhood Park           |   284 |   296 |             12 |
| Jointly Operated Playground |   262 |   262 |              0 |
| Playground                  |   249 |   251 |              2 |
| Community Park              |   106 |   114 |              8 |
| Nature Area                 |    86 |    93 |              7 |
| Recreation Field/Courts     |    68 |   nan |            nan |
| Strip                       |    68 |    68 |              0 |
| Undeveloped                 |    54 |    36 |            -18 |
| Mall                        |    34 |    34 |              0 |
| Parkway                     |    31 |    32 |              1 |
| Buildings/Institutions      |    23 |    20 |             -3 |
| Waterfront Facility         |    20 |    21 |              1 |
| Managed Sites               |    16 |    15 |             -1 |
| Flagship Park               |    15 |    15 |              0 |
| Cemetery                    |    14 |    13 |             -1 |
| Historic House Park         |    12 |    12 |              0 |
| Lot                         |     5 |     5 |              0 |
| Recreational Field/Courts   |   nan |    75 |            nan |
| Operations                  |   nan |     2 |            nan |
| Retired N/A                 |   nan |     1 |            nan |

**Comment by damonmcc** [comment]
@caseysmithpgh 
investigated the loss of an official cemetery

at some date between 1/9/2024 and 3/9/2024, the `typecategory` value for Joseph Rodman Drake Park & Enslaved African Burial Ground in the Bronx ([DPR page](https://www.nycgovparks.org/parks/joseph-rodman-drake-park/)) was changed from a `Cemetery` to a `Neighborhood Park`
