### ISSUE TITLE
Pluto 24v4 QA - Draft 1

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#1271]
QAQC [page](https://de-qaqc.nycplanningdigital.com/?page=PLUTO).

DO [link](https://cloud.digitalocean.com/spaces/edm-publishing?path=db-pluto%2Fdraft%2F24v4%2F1%2F).

Please refer to DE notes for this build in the parent GH issue.

**Comment by caseysmithpgh** [comment]
@jackrosacker, @sf-dcp and I met today to work through PLUTO QA and QA App updates. Final QA report is forthcoming, however our initial review left us with the following concerns: 
- 0 changed records on "mismatch graph -- finance fields". The issue specifically occurs when the comparison type is set to "Last of same version type". 
  - GIS suspects this may result from an issue in the streamlit app code rather than a source data issue. So before we determine whether to rebuild 24v4, Sasha is going to take a look at the QA app code to ensure there are no chart errors.
  - If there is not an bug in the chart configuration, GIS likely supports re-building 24v4 with Nov. Zoning (almost QA'd) and the DTM that was pulled by GIS on 20241122.
- Additionally, we discussed how the inconsistency between DE and GIS dated naming conventions also makes confirmation of source data (especially DOF DTM) challenging, specifically across multiple version comparisons. This is an issue GIS and DE hope to discuss as part of a future join venture.

**Comment by fvankrieken** [comment]
To the second point, we should chat, but we've recently moved those datasets from data library to our new tool which ensures that the date that you see for the DE "source data version" is the same as the date folder name in `edm-publishing/datasets`, rather than the date that it was archived by DE. The just run update (Nov zoning data) is the first time they've been archived using the new tool.

**Comment by caseysmithpgh** [comment]
> To the second point, we should chat, but we've recently moved those datasets from data library to our new tool to archive DE source data which ensures that the date that you see for the DE "source data version" is the same as the date folder name in `edm-publishing/datasets`, rather than the date that it was archived by DE. The just run update (Nov zoning data) is the first time they've been archived using the new tool.

Oh cool, would be interested to hear more about this!

**Comment by jackrosacker** [comment]
Thanks for following up on this. Glad we can pass QA for this specific metric. We still have to run through the final tables in the QA app before fully passing, but should get to that today or tomorrow.

**Comment by caseysmithpgh** [comment]
### PLUTO 24v4, Draft 1 QA Results
Status: FAILED
Needs: Manual corrections prior to re-build. 

#### Summary: 
A close review of the unreasonably small apartments table has resulted in the need for corrections (see table below). The majority of these corrections are for over reporting of unitsres, however reseach on two BBLs indicated under reporting. Please double check those that were allegedly under reported: `1010460160` and `2026037501`.

@AmandaDoyle is going to advise further on QA of the following tables. Potentially worth waiting on re-build until additional review of these tables.
- table of BBLs where bldgarea/lotarea > numfloors*2
- New and Vanished BBLs



<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/c_smith/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/c_smith/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


BBL | FIELD | OLD_VALUE | NEW_VALUE | TYPE | REASON | VERSION | Link
-- | -- | -- | -- | -- | -- | -- | --
3013347501 | unitsres | 64 | 8 | Research | PTS   error – units | 24v4 | https://streeteasy.com/building/1607-pacific-street-brooklyn
3032957503 | unitsres | 140 | 20 | Research | PTS error – units | 24v4 | https://streeteasy.com/building/23-bleecker-street-brooklyn
1008017504 | unitsres | 169 | 13 | Research | PTS   error – units | 24v4 | https://streeteasy.com/building/128-west-26-street-new_york/8
3053027502 | unitsres | 72 | 6 | Research | PTS error – units | 24v4 | https://streeteasy.com/building/182-minna-street-brooklyn
4050767502 | unitsres | 149 | 30 | Research | PTS   error – units | 24v4 | https://streeteasy.com/building/fowler-park
1010460160 | unitsres | 77 | 79 | Research | PTS error – units | 24v4 | https://streeteasy.com/building/354-west-56-street-new_york
2026037501 | unitsres | 65 | 135 | Research | PTS   error – units | 24v4 | https://streeteasy.com/building/540-southern-boulevard-bronx
3019147512 | unitsres | 103 | 18 | Research | PTS error – units | 24v4 | https://streeteasy.com/building/904-bedford-avenue-brooklyn/1b



</body>

</html>


@sf-dcp @fvankrieken @damonmcc @alexrichey 
FYI @jackrosacker @croswell81

**Comment by caseysmithpgh** [comment]
@sf-dcp 
Discussed with Jack, and we think using latest zoning and DTM would be best

**Comment by AmandaDoyle** [comment]
Hi all - I met with Sasha and reviewed the the rest of the QAQC table.  Once the additional manual corrections made by the GIS team are incorporated PLUTO can be rebuilt.  Given that there are no issues with the source data and in a effort to get this PLUTO major out asap, we'll keep the source data as is.  We will release a 2 PLUTO minors with updated zoning data for December and January.  We will kick off PLUTO 25v1 on February 25 after the 25A release of Geosupport.

**Comment by sf-dcp** [comment]
@jackrosacker, sounds good. Yes, we will keep all source data the same. I'm working on corrections today; after that I will re-build and promote to draft if everything looks good.

@caseysmithpgh, I'm going through the corrections list now, and the bbl `1010460160` doesn't appear to need a correction. Using your link, it mentions 77 and 79 units as shown below: 

![Image](https://github.com/user-attachments/assets/23f54954-85ec-4177-80e0-94a6724724c0)

Looking at PTS data, this bbl has residential and retail areas: so the extra 2 units are probably the retail space, aligning with the street easy link.
