### ISSUE TITLE
DevDB Enhancements for GIS

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#21]
Continuing [this project](https://github.com/NYCPlanning/edm-overview/issues/905) 

Project plan outlined [here](https://nyco365.sharepoint.com/:w:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7BA8DA99B5-0FCC-488B-BF48-90AA087AD8BE%7D&file=Project%20statement%20-%20HousingDB%2023Q2%20enhancements.docx&wdOrigin=TEAMS-ELECTRON.teams.chiclet&action=default&mobileredirect=true&cid=e46b6d08-4864-49fb-8f2c-76e6d06e00f1)

Changes to outputs need to be made in addition to current outputs, so current thought is to include a zipped "publish" folder within the current output folder that has necessary tweaks to schemas, data filtering/changes, etc

Still in-progress list of todos (as in still missing items as scoping out continues)
- Project-level files
  - [x] scope out changes needed
  - [x] generate output versions of housingdb with various filters
  - [x] export as both shp and csv
- Unit change summary files
  - [x] update schemas to match outputs (not 100% but framework for exporting different column names is there)
  - [x] filter "current year" data based on build version (22Q4 should not have 2023 data, 23Q2 should)
  - [x] for aggregates by geographic area, include those with 0 rows
  - [x] output shapefiles in addition to csvs
  - [x] See section 6 in [Housing DB Data Production instructions_20220909_update.docx](https://nyco365.sharepoint.com/:w:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/DATA%20ENGINEERING/DevDB/Housing%20DB%20Data%20Production%20instructions_20220909_update.docx?d=w40f84a847de64715a1f047d9899c0114&csf=1&web=1&e=VokmQX) to know how to address NULL values and calcualte fields.  Information is highlighted in yellow.

**Comment by fvankrieken** [comment]
Unit change summary files effectively finished for first round, a couple todos
- [ ] finalize schemas, and check in with maybe both AD and SL - could internal export use same schema as bytes? Should bytes output actually match data dictionary that comes from bytes? Currently it does not, capitalization is not consistent with data dictionary
- [ ] review shapefile outputs with GIS team

**Comment by fvankrieken** [comment]
Same issue around project-level files - currently column headers do not match data dictionary - in this case, not only capitalization issues, but column headers simply don't match for all outputs. For example, data dictionary gives header "Nonresid_Flag" but output csvs have "NonresFlag". Headers currently match what shapefile output for devdb and housingdb (from our pipeline) have.

Seems like it'd be worth normalizing - maybe checking in with SL and seeing if we can just get away with one set of columns across internal/external csv/shp exports (and aligned with external data dictionaries obviously)

**Comment by fvankrieken** [comment]
Getting a warning with some shapefile export fields

> Warning 1: Value 595419183.113000035 of field shape_area of feature 69 not successfully written. Possibly due to too larger number with respect to field width

Seems to be this https://trac.osgeo.org/gdal/ticket/6803

Need to investigate to see what's actually happening to field values

**Comment by fvankrieken** [comment]
Related to https://github.com/NYCPlanning/db-developments/issues/644 as well

**Comment by fvankrieken** [comment]
Sounds good - any thoughts on folder structure? Couple ways to slice it/name things and I can't quite make up my mind. Maybe change `aggregate` to `unit_change_summary_internal` and then have `project_level_internal` and `project_level_bytes`? Or `external` rather than `bytes`? Or just one `bytes` folder rather than split by unit change summary vs project level

**Comment by AmandaDoyle** [comment]
@fvankrieken 
Here are my notes
-Unit Change Summary Files look good
- Project level files
When comparing [HousingDB_post2010](https://s-media.nyc.gov/agencies/dcp/assets/files/zip/data-tools/bytes/nychdb_22q4_shp.zip) from Bytes aka `housingdb_post2010_bytes` to your output [HousingDB_post2010.shp.zip ](https://edm-publishing.nyc3.cdn.digitaloceanspaces.com/db-developments/main/latest/output/bytes_project_level/HousingDB_post2010.shp.zip) aka `housingdb_post2010_finn` in Carto
I noticed the following
- housingdb_post2010_bytes has 72 columns, but housingdb_post2010_finn has 69 columns.  I think you have fewer columns because we're removing all 6 of the 2010 fields (i.e. `bct2010`) so this is right and you're targeting 66 columns.
- Remove `job_inactv`, `datasource`, and `desc_other` columns from housingdb_post2010_finn, and this should get you the right columns.
- housingdb_post2010_bytes has 95331 rows, but housingdb_post2010_finn has 72415 rows.  I would not expect the number of rows to decrease.  I can't figure out what the difference may be.  Do you have any sense?  If not, I'm happy to keep digging in.

**Comment by fvankrieken** [comment]
Ah. I tried to be clever with how I was dropping job_inactiv but managed to not drop it from the shp files, only csv. Sounds good re that and the other columns. 

Re rows, this is the issue that the bytes data includes all inactive jobs as well (as in, it's the wrong file)

**Comment by damonmcc** [comment]
@fvankrieken good to close this? 🤞🏾
