### ISSUE TITLE
DE<>GIS Automations - Phase 1

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#281]
This phase covers scoping, exploration, and trying discussed approaches on a couple of datasets (likely to be MIH and COLP).

## Glossary
`packaging` - data and metadata transformations that happen prior to push to other data stores (e.g. Socrata)
`flow` - a movement of data. It could be a push or a pull.
`metadata` - 
- attachments (pdfs, etc.), 
- file-level (ie baked into shapefiles), 
- external system data (ie Socrata `Legislative Compliance` section, or contact info)

## Tasks
- [x] #353
- [x] #393
- [x] #427
- [x] #426
- [x] #268
- [ ] #623

**Comment by damonmcc** [comment]
OTI PDF which details Open Data self-publishing option: [link](https://opendata.cityofnewyork.us/wp-content/uploads/NYC_OpenData_AgencySelfPublishingGuidelines.pdf)

**Comment by alexrichey** [comment]
Also shared, [DCAT](https://www.w3.org/TR/vocab-dcat-3/) standards

**Comment by alexrichey** [comment]
Takeways from meeting with GIS on Oct 13.
- [Open Data Guidelines](https://opendata.cityofnewyork.us/wp-content/uploads/NYC_OpenData_AgencySelfPublishingGuidelines.pdf) lists several ways to upload data to OpenData/Socrata. There are two or three options (sdks/publishing api/rest api) that we're going to POC.
- We'll focus first on pushing data from AGOL (ArcGIS Online) -> OpenData/Socrata because this could be the most standardized and repeatable data flow, due to AGOL's enforced data standards. 
- Then we'll try going from Digital Ocean to OpenData/Socrata. This may be more difficult because data on Digital Ocean are largely shapefiles.
- We have a test dataset for [MIH](https://data.cityofnewyork.us/dataset/MIH_Test/p6cc-cxkc/revisions/0) (Mandatory Inclusionary Housing) here. We'll push to this for testing. 
- This sprint will be largely exploratory work.

**Comment by alexrichey** [comment]
![GDE-Dataflow](https://github.com/NYCPlanning/data-engineering/assets/11164730/03ab994d-d31e-44fb-886d-4d04d6a8584f)

Notes:
- SDE is an ESRI Spatial Database Engine, which is effectively git for geographers. 
- ~80% of data at GDE is accounted for by this path. 

The scope for this initial phase is to draw a line straight from AGOL to OpenData. Currently OTI receives OpenData updates via email, and OTI would like very much to have this process automated.

**Comment by alexrichey** [comment]
[Options for pushing to OpenData](https://opendata.cityofnewyork.us/wp-content/uploads/NYC_OpenData_AgencySelfPublishingGuidelines.pdf)

- [Socrata Gateway](https://support.socrata.com/hc/en-us/sections/360005092553-Socrata-Gateway)
Agent (a running process on our servers) that will configure itself by phoning home (to Socrata) and push data on a schedule. It exposes data syncing functionality, but not metadata. Conceivably you could run this on a machine behind our firewall to sync data to Socrata. Probably not worth due to the limitations of syncing just data.

- [Socrata-py](https://github.com/socrata/socrata-py#metadata-only-revisions)
Fully featured python client. Docs say it hits the `Socrata Data Management API` but it hits the publishing REST API as well. **Our best option**. I've tried pushing datasets, metadata, etc. and it's straightforward.

- [Publishing API](https://socratapublishing.docs.apiary.io/#)
Umbrella for a few different APIs (SODA Producer API, Dataset Management API, Import API)

- [Metadata API](https://socratametadataapi.docs.apiary.io/#introduction/use-cases)

Misc
- [sodapy](https://github.com/xmunoz/sodapy) - Dead Python Client
- [Socrata DataSync](https://socrata.github.io/datasync/) - Java jar you can download and run. Basically a GUI layer over the data API. Not worth it, due to limitations.
- [Connectors](https://dev.socrata.com/connectors/safe-fme.html)
Proprietary connectors for Socrata and other sources. Plugins are largely declarative, and one exists for ESRI. Built by a partner company, and you need an account with them, so it's probably not worth the time.

**Comment by alexrichey** [comment]
- Can we push from DO to AGOL? 
- Wrinkle: have to name differently for DO and destinations

Next Steps:
- Prove out pushing to AGOL
- Exercise: take a handful of Data Engineering's products, and map formats. 
  - start with: housing, cpdb, pluto, facdb
  - what metadata goes with diff products.
- Metadata
  - how would it be applied?
- Tommy (former intern) wrote PHP app to package for ESRI. Investigate *
- * Design should think about metadata on shapefiles
- Data dictionaries don't have spatial details, projectsion. ESRI metadata already has it. 

Notes:
- Filenames on Bytes may change imminently (ie in the next month+)
- DE needs scoped AGOL creds
- Alex Finckel would be able to help pulling from AGOL (OTI)

**Comment by croswell81** [comment]
Adding two diagrams of GIS open data process:
Original:
![image](https://github.com/NYCPlanning/data-engineering/assets/33908810/95f380f9-836f-461a-8e7e-19d0391fc8ac)

More recent: when @jackrosacker returns he can add the other diagram.

**Comment by croswell81** [comment]
@alexrichey FYI - Alex from OTI open data team shared the following resources:

- Tyler Metadata API information: [https://socratametadataapi.docs.apiary.io/#](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsocratametadataapi.docs.apiary.io%2F%23&data=05%7C01%7Cmcroswe%40planning.nyc.gov%7Cb01394d01dde455f57ad08dbdb149fd6%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638344654671297953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=RfTCyNMHDTTMwHYt%2Fml6PT14Z6VNbt6lgCX74fatPwk%3D&reserved=0)
- Socrata Support page: [https://support.socrata.com/hc/en-us](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.socrata.com%2Fhc%2Fen-us&data=05%7C01%7Cmcroswe%40planning.nyc.gov%7Cb01394d01dde455f57ad08dbdb149fd6%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638344654671297953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=0xgBjAwHUAsWC%2FEoS9EJgc9jtmCYGvFe7vbor8DMjVI%3D&reserved=0)

**Comment by caseysmithpgh** [comment]
@alexrichey Here's the updated diagram. I did my best to include bits from the whiteboard yesterday, and synthesize some of our thoughts on "phases". Looking forward to hearing your thoughts once we're both back in the office. 

![casey_proposal_updates](https://github.com/NYCPlanning/data-engineering/assets/73206018/3206615b-a351-4e6a-8fde-6cdfff84a6c8)

**Comment by croswell81** [comment]
@alexrichey to answer the question, **Is there a comprehensive list of DCP datasets on Socrata?** - unfortunately its not that straightforward since there is not a one-to-one match of all data on BYTES of the BIG APPLE (BOBA) and NYC Open Data portal.

1. This is OTI's [list ](https://data.cityofnewyork.us/City-Government/Local-Law-251-of-2017-Published-Data-Asset-Invento/5tqd-u88y)they generate as all datasets on the **NYC Open Data porta**l, which can be filtered by agency

- I feel like this is not comprehensive
- Some data is not uploaded to portal, and only a link back to BOBA

2. Recommend you use this [list](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/GIS/Open%20Data/[Open_Data.xlsx](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/GIS/Open%20Data/Open_Data.xlsx?d=w6735537b8d8e437ab5e53a6b54194b24&csf=1&web=1&e=8xTJ8m)?d=w6735537b8d8e437ab5e53a6b54194b24&csf=1&web=1&e=8xTJ8m), which is our list we use to track open data updates and send to OTI. We just added open data UID and URL as fields in this table.

**Comment by alexrichey** [comment]
Next Steps

### Checklist for datasets

- [ ] Is it in DO? If so where
- [ ] Is pushing to DO?

### Process for GIS to onboard datasets to push to DO

- [ ] Adding Product metadata
- [ ] Adding product do `edm-distributions`

### Get Other DE Team members involved


### Planning Metadata for Products
- With Amanda, GIS, and DE
- Figure out data formats, location
