### ISSUE TITLE
Add checkbook nyc (via API) to data library

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#312]
[Checkbook NYC](https://www.checkbooknyc.com/spending-api) data is specified in data library via two templates
- [`cpdb_capital_spending`](https://github.com/NYCPlanning/data-engineering/blob/main/products/cpdb/templates/cpdb_capital_spending.yml) - input to CPDB (being phased out)
  - [Workflow to archive](https://github.com/NYCPlanning/data-engineering/blob/main/.github/workflows/archive/cpdb_spending.yml), this actually calls the [logic that generates the file ](https://github.com/NYCPlanning/data-engineering/blob/main/products/cpdb/bash/06_spending.sh)
- [`nycoc_checkbook`](https://github.com/NYCPlanning/data-engineering/blob/main/data-library/library/templates/nycoc_checkbook.yml)

Both currently have issues. `nycoc_checkbook` is just raw checkbook data, which is what this dataset ideally is. But it comes from a local csv rather than accessing via the checkbook nyc web api. The former is a bit more convoluted - it calls shell scripts to do some processing in bigquery, using bigquery as the source for checkbook data. It then dumps the results of these bq queries to a csv, which then gets archived with data library.

How does checkbook nyc data end up in bigquery? These two repos have the code to do it: [db-airflow](https://github.com/NYCPlanning/db-airflow/tree/main/dags) and [db-checkbooknyc](https://github.com/NYCPlanning/db-checkbooknyc/tree/main) (I actually somehow missed this in the past and only found it while looking for db-airflow). Neither has workflows run, so I'm not sure when/how it was actually being used.

So moving forward, an ideal solution would be to 
1. only have one data-library dataset for checkbook, `nycoc_checkbook`
2. use logic currently in db-airflow/db-checkbooknyc to pull data from api (via `script` source in `nycoc_checkbook` template

**Comment by sf-dcp** [comment]
### Preliminary findings: 

According to the API [docs](https://www.checkbooknyc.com/data-feeds/api): 
* Data should be sent/received via **HTTP POST** request.
* Requests and responses are in XML format.
* There are multiple domains available via API: `Contracts`, `Budget`, `Revenue`, `Payroll`, and `Spending`. We are focusing on `Spending` only for this issue.
* For all domains, there are 3 global parameters that you query on:
    * `type_of_data` (required). Options: `Contracts`, `Budget`, `Revenue`, `Payroll`, and `Spending`. Note, the options are for citywide expenses.
    * `max_records` (optional). The API limits up to a maximum of 20,000 records per call. For the `Spending` category, the default `max_records` equals to 20,000.
    * `records_from` (optional). 

* For all domains, there are global and/or domain-specific optional parameters.
* In the request to API, you can specify criteria parameters based on `value` or `range`. 

### Need to figure out: 
* As of 11/6/2023, there are 37 million records in the `Spending` dataset. How do we want to go about refreshing data? Do we want to rewrite the data every time or use incremental approach? We would need to make about ~200 calls to the API to get the entire dataset (if all calls are successful). 

* Whether the order of records at the source is deterministic. If we use the `records_from` parameter in our calls to the API, the order must be consistent. Otherwise need to figure out criteria to query on. 

* How to deal with failed calls.
