### ISSUE TITLE
CEQR Schools 2024

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#429]
## motivation

Capital Planning, Population, EARD, and the SCA need updated CEQR School data from us by February to update the "schools multiplier" the SCA uses to estimate the impacts of new housing on schools

## details

Source data to update in the `recipes` db via data library:
- [x] sca_bluebook
- [x] sca_capacity_projects_current
- [x] sca_e_pct
- [x] sca_e_projections

Expected to generate 4 datasets:
- [x] sca_capacity_projects
- [x] sca_e_projections_by_boro
- [x] sca_e_projections_by_sd
- [x] ceqr_school_buildings

## notes

We currently consider CEQR Schools and CEQR Air as two separate products. Is this a distinction worth preserving from DE's perspective since:
- they're updated at nearly the same time/frequency
- the code for both are coming from a single repo so it may take some time to untangle/abstract them enough to avoid duplicate code
- we likely want to minimize our list of distinct products

or do we want a future with many data products that have fewer files in their subdirectories, are defined by their transformations of source data, and only use shared utils?

**Comment by damonmcc** [comment]
due to urgency and complexity of CEQR build code will likely run builds locally, share outputs, and refactor to be like other products later

**Comment by damonmcc** [comment]
outputs go to `/edm-publishing/ceqr-app-data-staging/`

**Comment by damonmcc** [comment]
shared 20240110 build outputs with Capital Planning for QA

**Comment by damonmcc** [comment]
awaiting sca_capacity_projects address corrections from Capital Planning. link to latest corrections csv [here](https://github.com/NYCPlanning/data-engineering/blob/main/products/ceqr/recipes/_data/sca_capacity_address_cor.csv)

cc @mbh329

**Comment by mbh329** [comment]
The `sca_capacity_projects` dataset that is generated is essentially a list of Schools that are planned to be built over different SCA Capital Plans (the code appends them into one list of schools). 

1. it looks like DE geocodes the latest data and appends to the existing dataset in data library but we aren't accounting for schools from earlier Capital Plans that have already been built so I think we can with a reasonable amount of accuracy remove drop schools/capacity projects that have a `start_date` before in 2022 (the column `start_date` is not the most intuitive column names and is the date where the schools is expected to open derived from a column in the source data) otherwise we could end up double counting Capacity Projects (projected) already in SCA's Bluebook (actual) which is critical to understanding school capacity in a specific School District/School Sub district. 
2. The column `capital_plan` should be updated each update with the latest capital plan information which I can send you moving forward but for example the newest editions were coded as `20-24` Capital Plan but the data I sent is actually the `25-29` Capital Plan. 

Those are the two big issues I remember specific to this output  but I can go through the code with you and point out what else I noticed - let me know how you want to proceed @damonmcc @fvankrieken - not urgent though

**Comment by damonmcc** [comment]
@mbh329 appreciate the details. you mentioned in Teams that you manually fixed some things with the outputs. are these two things what you fixed?

either way, I'm happy to call these two things bugs and fix them as part of this data update issue

for reference, the PR that made the latest changes for this data is https://github.com/NYCPlanning/data-engineering/pull/503

**Comment by damonmcc** [comment]
closing this due to data passing QA after manual edits by Capital Planning, low urgency to automate those edits, and low bandwidth
