### ISSUE TITLE
Unknown Character in FacDB output

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#500]
# What:
When reviewing different versions of FacDB outputs (23v2 from Bytes, 24v1 draft), @jackrosacker noticed that the total count of records differed between csv and geodabase formats. Specifically, there were fewer records in geodabase. After further digging, Jack found that some records in csv output included a weird character which caused ArcGIS to omit all records after its first occurrence: 
* Opened via VSCode: 
   ![Screenshot 2024-01-09 at 2 18 33 PM](https://github.com/NYCPlanning/data-engineering/assets/144725249/367db043-27e3-4ccc-bbfc-fd2d2f906b19)
* Opened via Excel: 
   ![MicrosoftTeams-image](https://github.com/NYCPlanning/data-engineering/assets/144725249/13ed2068-526d-42e2-bb8b-17b351dab4cd)
* Opened in ArcGIS: 
![MicrosoftTeams-image (1)](https://github.com/NYCPlanning/data-engineering/assets/144725249/1528c441-5f94-4d4d-b9b9-21b4d05ad195). 

As seen in the last 2 screenshots, ArcGIS shows a total of 5,935 records, stopping at the first occurrence of the unknown character. 

# Next steps: 
* Investigate all data products that may have a similar issue

**Comment by sf-dcp** [comment]
> Assuming this can be closed?

@fvankrieken, No, it hasn't been investigated.

**Comment by damonmcc** [comment]
for the latest FacDB build from nightly QA, I compared row counts between the FGDB, CSV, and Shapefile. all three have 35252 rows

I looked at this record in the source data and final table and the value in the `FACNAME` column:
- looks like `YOUNG MENS CHRISTIAN ASSOCIATION OF GREATER NEW YORK`
- copies as `YOUNG MENS CHRISTIAN ASSOCIATION OF GREATER NEW YORK`
- inspecting it, I find that `\u1a` is in between the N and S

since I got the right row count when openning the FGDB via geopandas, it seems like ArcGIS has a problem with the character `\u1a`

**Comment by damonmcc** [comment]
found a sql query that seems to find records with `u1a` aka `x1a`, a [unicode escape sequence](https://stackoverflow.com/questions/16255585/what-does-the-x1a-characters-mean)

<img width="665" alt="Screenshot 2024-07-08 at 9 43 15 PM" src="https://github.com/NYCPlanning/data-engineering/assets/7444289/32002bb1-605c-4c67-9205-228fd2d9d306">

**Comment by sf-dcp** [comment]
From the link you provided: "\x1A is the CTRL+Z control character. It is also EOF marker". <-- yikes
