### ISSUE TITLE
CEQR Survey outputs

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#590]
The survey GIS is making must display the flags for all BBLs in PLUTO and the spatial source data that was used in the flag logic.

## Goals
- [x] export wide BBL table with BBL geometries
- [x] export variable details seed table and source data versions
- [x] export spatial source data (buffered and pre-buffered)

## notes
- There is non-spatial source data that informs the Zoning and (E) Designation flags, but we aren't exporting that tabular data. Those are qualities of the BBLs that aren't a high priority to show in the survey POC

**Comment by fvankrieken** [comment]
Hi @jackrosacker, just wanted to start getting down some specifics around outputs for this and make sure we're on the same page as you.

We sort of have two broad issues
- output tables/layers - the actual data and structure within
- packaging of these tables/layers (zipped folder, shapefile, gdb, etc)

## Output Tables
Breaking these into two categories
- source data/buffers (no logic around "flagging" bbls)
- computed outputs (i.e. the _actual_ outputs tables with flags included, whether aggregated by bbl or not)

### Source data/buffers
En route to producing final outputs, we have intermediate tables with buffered geoms. The tables look something like this (imagine those geoms are in 2263)
|variable|id|buffered_geom|
|--------|--|----|
|elevated_railway|14 STREET/CANARSIE LINE|POLYGON ((-73.91110564962213 40.685452360859514, -73.91110564954899 40.68545236162799)|
|elevated_railway|6 AVENUE LINE|POLYGON ((-73.91110564962213 40.685452360859514, -73.91110564954899 40.68545236162799)|

![image](https://github.com/NYCPlanning/data-engineering/assets/9454672/95ddf965-68e3-4dbb-9eae-7386b58e498b)

`variable` corresponding to the unique variable that there can be a flag for, `id` being a unique identifier of a given variable within its variable type. There are some outstanding questions on how these should be exported
- Do we want separate tables per `variable` ("elevated_railway" in this case), or 1 table that has "elevated_railway", "air_vent", "cat_permit", etc
- should they be melted/unioned? As in 1 geometry per `variable`, rather than 1 geom per id (in this case, segment of elevated railway)
- does the answer around separate tables vs 1 table change if melted?
- are unbuffered geoms desired as well? As separate columns in the same table(s), or separate table(s) from the buffered table(s)? Same questions exist around melting vs keeping rows distinct.

### Computed outputs (actual outputs)
We were planning on having our "long" table of flags included, let us know if you'd prefer us to leave it out. In this table, each row is a "flag". Any bbls with no flags will not be found in this table
|bbl|variable|variable_id|
|-|-|-|
|1000010001|elevated_railway|14 STREET/CANARSIE LINE|
|1000010001|edesignation_noise|1|
|1000010002|elevated_railway|14 STREET/CANARSIE LINE|

This could also include a "distance" column (for geospatial flags - edes in this case doesn't apply), for distance from noted variable

We are also going to include some form of wide format
|bbl|elevated_railway|edesignsation_noise|...|
|-|-|-|-|
|1000010001|14 STREET/CANARSIE LINE|1|...|
|1000010002|14 STREET/CANARSIE LINE|`NULL`|...|

There was also desire for some explicitly binary output, using `1` or `0` for easy calculation within [name of esri product]

A few questions to be resolved
- is bbl geom desired in these?
- For the wide format, we only want closest spatial flag if there are multiple for a given bbl/variable, correct?
- For binary output, would you want them as additional columns in the same wide table? Or a separate table?
  |bbl|elevated_railway|elevated_railway_bool|edesignation_noise|edesignation_noise_bool|...|
  |-|-|-|-|-|-|
  |1000010001|14 STREET/CANARSIE LINE|1|1|1|...|
  |1000010002|14 STREET/CANARSIE LINE|1|`NULL`|0|...|
- In a wide format, would you want number of flags for a given variable? If there are two elevated railways within 1500 ft, should that be reflected in any way in the wide format or should we only see the closest (and potentially a `1` in the bool column)
- Should we include other info about `variables`? Have them in a nicer display name rather than "elevated_railway", or include the question they map to. The latter might be a bit tougher in the wide format (at least in terms of including all relevant `variable` metadata), but we can figure something out

### Other tables
Is there anything missing in above summary? Say, a lookup table of variable, data source it comes from, question it relates to, etc.

## Packaging
@damonmcc was under the impression that one gdb might be the most convenient, is that true?
