### ISSUE TITLE
Capital Projects Map kickoff meeting

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#764]
The meeting is scheduled for 4/22 with all teams working on the project. We'll outline the project's goals, timeline, and planned tasks during the meeting.

This issue can be used to address expectations and details of the project that the team feels are important to clarify before work begins.

**Comment by TylerMatteo** [comment]
Hey @damonmcc, just thought I'd share a link to [18F's Product Guide](https://guides.18f.gov/product/). Not sure how much of this will be relevant to this project, but some of it might be useful in prepping for the kickoff meeting.

**Comment by jpiacentinidcp** [comment]
Importing key notes from fact-finding conversation on 3/26/24:

**Project Background and Scope**

With a new version of CPDB releasing, users need a way to download relevant Capital Projects based on geographic selection/filter. We need to develop a way to let a user download the number and types of projects within a specific geographic area, and get the associated commitments and budgets in that area.

We have determined the primary geographies of interest are Community Districts and City Council Districts. Borough level data aggregation may also be valuable.

Key user groups include Community Boards, Council Members' Offices, as well as other private and public organizations involved in capital funding and development. DCP's Borough Offices often liaise with many of these outside users, and they sometimes request specific areas of the database.

**Data Considerations**

Roughly 40% of the projects are geo-spatially mapped.

The remaining 60% are either mappable but not mapped, or fundamentally not geo-spatial and cannot be mapped.

Dataset itself may need to have an additional data columns so that it can be more easily filtered, especially if a Capital Project intersects multiple geographies. We have to determine best way to set up the dataset and the app so that it can detect projects by geography, as well as either display or allow export of non-mapped projects.

Data should be downloadable in CSV format. We can explore if mapped projects should also be available in SHP.

**UI/UX Considerations**

Given that so much data is not mapped, we will need some user affordance to indicate that these projects will not show up in a map view (if we determine to show individual projects on the map) Non-mappable data can be shown in a table or downloadable.

Having an interactive map dashboard would be helpful but there isn't a clear sense of what that might look like or what the functionality would be.

**Comment by TylerMatteo** [comment]
@jpiacentinidcp @damonmcc  thoughts on having a portion of the presentation define how we are [measuring success](https://guides.18f.gov/product/deliver/measure/)? This would have some overlap with the "Outcomes" defined in the project plan but I think we could come up with some things that are more user-centered. Things like:

* DCP staff spend less time responding to data requests for Capital Projects in a given area
* City Council staff retrieve data for relevant Capital Projects without having to interact with a human at DCP

versus "A new app exists that does x, y, and z" can help to focus us on the _why_ instead of the _what_.

**Comment by jpiacentinidcp** [comment]
@damonmcc @TylerMatteo I definitely think measuring success should be a part of the kickoff conversation

**Comment by TylerMatteo** [comment]
Hey @damonmcc I'm assuming we'll want to have a slide deck? I'm happy to contribute but want to follow your lead. If we are having one, has it been started yet?

**Comment by damonmcc** [comment]
@TylerMatteo wasn't planning to have a slide deck. seems like overkill and that it'd lead to important info (like how we'll measure success) living in more than one place since anything that's important should probably be in a more accessible/permanent place

since the meeting is to "outline the project's goals, timeline, and planned tasks", seems like we can do all that with the project issue and prioritize time for questions/discussion

and if we wanna go into details that aren't in the project issue, we can navigate to those resources (like the CPDB slides Amanda made)

**Comment by damonmcc** [comment]
## notes from kickoff meeting
### measures of success
- need baselines for things like "# of requests for data", may be best to have Capital Planning estimate these
- should add measures related to use of new AE app like visit and data downloads

### app vs app
- the Experience Builder app is meant to satisfy the urgent need for a map, the custom AE app is meant to replace it
