### ISSUE TITLE
new GRU QAQC report

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#812]
Geographic research would like to add a new QAQC report to the portfolio of existing [GR QAQC reports](https://de-qaqc.nycplanningdigital.com/?page=GRU+QAQC).

This new report would compare Historic Footprint BIN vs PAD BIN. This is essentially a version of the existing BIN vs PAD BIN, but using historical data.

Geographic Research would like to be able to run this new report after 24B is released on May 5 to clean up the data ahead of the 24C release.

[This](https://data.cityofnewyork.us/Housing-Development/Building-Footprints-Historical-Shape/s5zg-yzea) is the best place for DE to get historical footprint data (already in edm-recipes)

**Comment by fvankrieken** [comment]
This will need stuff to happen in a couple places

Running of GRU QAQC happens in another repo : https://github.com/NYCPlanning/db-gru-qaqc. This could be moved at this point, because I've removed most of the automation around issues and github actions within the repo in favor of the page on the streamlit app. But that doesn't need to happen now.

In that repo, we'll need
- [ ] a new bash script
  - properly named
  - generates outputs and exports/uploads just like the other datasets 
- [ ] presumably, a new python script
- [ ] ensure that the main gha can call the target script

Then, in the qa app, we'll need this added as an option for GRU. I __think__ this is largely abstracted, and there's just a csv/dataframe that will need a row added for this test

**Comment by fvankrieken** [comment]
This test should be called `historic-footprints-vs-pad`
