### ISSUE TITLE
new directory structure in DO like `build` -> `draft` -> `publishing`

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#960]
pretty much #825

**Comment by fvankrieken** [comment]
A couple thoughts on random features that would be nice

- when ztl data loading action runs and builds ztl, it'd be nice to immediately promote the build to a draft, since GIS runs this job with the explicit purpose of generating a draft
- maybe in general, it'd be nice to have a checkbox in build.yml allowing to directly promote to draft

**Comment by sf-dcp** [comment]
> A couple thoughts on random features that would be nice
> 
> * when ztl data loading action runs and builds ztl, it'd be nice to immediately promote the build to a draft, since GIS runs this job with the explicit purpose of generating a draft
> * maybe in general, it'd be nice to have a checkbox in build.yml allowing to directly promote to draft

Could you clarify if both of these or one of these bullet points should be true?

**Comment by fvankrieken** [comment]
I would say both - for the ztl dataloading action, we don't need to provide the choice exposed to users, just automatically do it. For `build.yml` it should be a boolean input
